import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import LogInWrapper from "@/components/LoginWrapper/LoginWrapper";
import { UserProvider } from "@/utils/contexts";

export const metadata: Metadata = {
  title: "TheMealDB",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={``}
      >
        <Header />
        <UserProvider>
          <LogInWrapper children={children}  /> {/* page.tsx */}
        </UserProvider>
      </body>
    </html>
  );
}
